version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/locations:/etc/nginx/locations
    networks:
      - paas_network

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - paas_network

  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/locations:/app/nginx_locations
    networks:
      - paas_network

  frontend:
    build: ./frontend
    container_name: vite_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - paas_network

volumes:
  mongo_data:

networks:
  paas_network:
    name: paas_network
    driver: bridge